### ISSUE TITLE
Have you initialized to integrate your Extension in the official certbot Image?

### ISSUE THREAD

**Issue by MBeKde** [kraiz/certbot-dns-euserv#1]
Hi,
have you always requested to integrated your extension into the official Certbot Image?
Would make live much easier.
I wrote myself a similar extension für acme.sh and fortunately they included it into the official Release.

Thanks
Michael

**Comment by mschoettle** [comment]
Hi @initit,

I created EUserv provider support for lexicon with the new API (which also has a proper SSL certificate). I opened a PR to get it included in lexicon.

Does either of you (@initit or @kraiz) have a domain contract with EUserv containing multiple domains? I am wondering how the description field of the contract (which contains the domain name) looks like.

**Comment by MBeKde** [comment]
Hi Matthias,
Sorry, but i‘ve moved all my domains a few months ago to Hosting.de cause they have a modern API (yes, i’ve recognized that euserv also has modified their API, but to late), very responsible and very inexpensive.
So, no, i’ve no domains anymore at euserv.
Regards
Michael

**Comment by mschoettle** [comment]
No problem. Was just curious how multiple domains are separated in the description. With one domain it is "contract name\ndomain.name".

Good to know. I saw your hosting.de lexicon provider. Do you use it in combination with certbot to automatically renew certificates? If so, how?

**Comment by MBeKde** [comment]
I wrote my own certbot provider, based on my lexicon extension (cause: 1. certbot was not accepting new providers a while; 2. it took a while to inclued my provider to lexicon))
So, i generate based on certbot a new docker image, install my hosting.de certbot extension and copy my own lexicon provider into this docker image ...

**Dockerfile**
`FROM certbot/certbot

RUN pip install --no-cache-dir dns-lexicon
RUN pip install https://github.com/initit/certbot-dns-hostingde/archive/master.zip
COPY ./lexicon /usr/local/lib/python2.7/site-packages/lexicon/providers/
`
Now, as certbot is accepting new providers and my extension is official part of lexicon, i would make a PR to certbot for my certbot/hosting.de provider ;)

Hope that helps.

**Comment by kraiz** [comment]
Sorry for being so unresponsive. I never requested integration as I can't maintain it. In the meantime I also moved my domains to an already supported provider.
